# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: yarn install
  - script: yarn build
  - task: CopyFiles@2
    inputs: 
      sourceFolder: 'build'
      targetFolder: '$(Build.ArtifactStagingDirectory)/edu'
  - task: PublishBuildArtifacts@1
    displayName: 'Upload Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/edu' 
      artifactName: 'teams-edu-event-creator'
  - task: DeleteFiles@1
    inputs:
      SourceFolder: 'build'
      Contents: '*'
      RemoveSourceFolder: true
  - script: yarn build:health
  - task: CopyFiles@2
    inputs: 
      sourceFolder: 'build'
      targetFolder: '$(Build.ArtifactStagingDirectory)/health'
  - task: PublishBuildArtifacts@1
    displayName: 'Upload Artifact'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)/health' 
      artifactName: 'teams-health-event-creator'